### PR TITLE
Replace constraint with konstraint

### PR DESCRIPTION
**Pull request by making**
so that developers can look up a right method with code completion quickly

https://github.com/making/yavi/issues/16

### CODE REVIEW

**Comment by sdeleuze** [comment]
I am not sure I like this change, let's discuss that on making/yavi#16 before moving forward here.

**Comment by making** [comment]
No problem. Welcome your feedback!

**Comment by sdeleuze** [comment]
See [my proposal for a validator DSL](https://github.com/making/yavi/issues/18).

**Comment by sdeleuze** [comment]
Done via 62e9d1a8a55870694377c0637af0aade07526670.

**Pull request closed without merging**
