### PR TITLE
#16: add spring security DSL

### PR DESCRIPTION
**Pull request by jonasbark**
Fixes https://github.com/spring-projects/spring-fu/issues/16 

This pull requests adds the possibility to configure Spring Boot Security via Kofu:

```
           security {
                http {
                    headers()
                    logout()
                }
            }
            webFlux {
                webFluxSecurity()
            }
```

I'm open to feedback, mostly regarding what DSL could be added. As mentioned in Kotlin Slack, let's have a quick chat about it on Spring I/O!

### CODE REVIEW

**Comment by sdeleuze** [comment]
@jonasbark Thanks for this contribution, this is a great start. You will find in [my branch](https://github.com/sdeleuze/spring-fu/tree/spring-security) some small changes, could you integrate them in this PR?

Also please use tabs for indent, I know that's not everybody taste but that"s what we use in Spring ;-)

I think next steps are:
 - Adding integration tests in `kofu` module
 - Adding a sample application
 - Add support for Spring MVC
 - Support more features in the security DSL

Do you have some time to move it forward?

**Comment by jonasbark** [comment]
Our company will focus on Spring Security soon so I'll be able to see which DSLs might be handy to have. A rough estimate would be four weeks from now.

**Comment by eanekrasov** [comment]
Any progress?

**Comment by sdeleuze** [comment]
We are working on a built-in Spring Security Kotlin DSL which should be available on Spring Security side, I will update this PR when it will be available.

**Comment by jonasbark** [comment]
Sounds good 👍 I caught up with work by now so I'm available to update the PR as well (once the 'offical' DSL is testable)

**Comment by sdeleuze** [comment]
https://github.com/spring-projects-experimental/spring-security-kotlin-dsl is about to be available ;-)

**Comment by pull-vert** [comment]
According to [Spring security Kotlin DSL](https://github.com/spring-projects-experimental/spring-security-kotlin-dsl/blob/master/README.adoc) :

> The native Kotlin DSL for servlet based applications has been integrated into Spring Security as of version 5.3.0.M1. Servlet based applications no longer need to add this (spring-security-kotlin-dsl) project as an additional dependency. Reactive applications should continue to use this project for a native Kotlin DSL

So this subject is back, at first for servlet based apps, Reactive seems to be nearly ready too !

**Comment by guitcastro** [comment]
So there is an ETA for kotlin security dsl to be integrated into Spring Security?

**Comment by pull-vert** [comment]
@guitcastro Kotlin security DSL is now fully integrated in [Spring Security 5.4.0-M1 milestone 1 release](https://spring.io/blog/2020/05/07/spring-security-5-4-0-m1-released) !

**Comment by sdeleuze** [comment]
This PR will be replaced by integration of this official support via 16.

**Pull request closed without merging**
