### PR TITLE
add JaFu Redis DSL

### PR DESCRIPTION
**Pull request by agebhar1**
This is WIP for #278 if it's the right direction I'll add (integration) tests.

* Cassandra DSL
* Redis DSL

I'm looking forward for feedback.

### CODE REVIEW

**Comment by sdeleuze** [comment]
Hi, thanks for your contribution, yes I think this is going in the good direction so please provide integration tests and I will review it more in depth before merging it.

**Comment by agebhar1** [comment]
Thanks for your reply. I will continue to implement the integration tests.

**Comment by agebhar1** [comment]
This PR is now reduced to the JaFu Redis DSL. The Cassandra DSL is requested by #286.

I added (basic) integration tests and I'm looking forward for your feedback.

**Comment by agebhar1** [comment]
@sdeleuze this PR is ready for review. Should there be detailed tests for each configuration (combination)?

After the review all commits could be squashed.

**Comment by sdeleuze** [comment]
We will review this PR shortly sorry for the delay.

**Pull request closed without merging**
