### PR TITLE
Kofu tutorial

### PR DESCRIPTION
**Pull request by lucapiccinelli**
A tutorial for KoFu as the follow up of this issue https://github.com/spring-projects-experimental/spring-fu/issues/20

### CODE REVIEW

**Comment by lucapiccinelli** [comment]
The tutorial is here https://github.com/lucapiccinelli/spring-fu/tree/kofu-tutorial/samples/kofu-tutorial

**Comment by lucapiccinelli** [comment]
@sdeleuze any feedback? 😇

**Comment by sdeleuze** [comment]
Looks great, I will squash the commits, check it works as expected, and merge it. Thanks for working on this.

**Comment by lucapiccinelli** [comment]
Thanks to you. It is a pleasure and an honor for me to have my name on an official spring tutorial. Do you think that this is going to be published under the spring tutorials pages, or it will stay only in this repo?

I wish there will be another chance to contribute in the future.
Thank you

**Comment by sdeleuze** [comment]
Merged, thanks a lot. It will stay on this repository since Spring Fu is not a top level project.

**Pull request closed without merging**
