### PR TITLE
#207 Add GraphQL support

### LINKED ISSUE #207: Add GraphQL support
See how to leverage https://github.com/graphql-java-kickstart/graphql-spring-boot in Kofu.

### PR DESCRIPTION
**Pull request by FVershinin**
Pull request attempts to fix #207

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@FVershinin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-fu&pullRequestId=233)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-fu&pullRequestId=233) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@FVershinin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-fu&pullRequestId=233)!

**Comment by sdeleuze** [comment]
First, thanks for this high quality PR, that's a very good start.

My current thinking is that the ideal outcome could be a big refactoring of https://github.com/graphql-java/graphql-java-spring to leverage functional routing and improve the WebFlux support based on what you have done in this PR, to keep only the Kofu DSL specific bits here. Any thoughts?

Also I would be interested to to know if you have checked that the `graphql-java` async supports is really non-blocking and not based on blocking code running on a thread pool via a dedicated executor.

**Comment by FVershinin** [comment]
> My current thinking is that the ideal outcome could be a big refactoring of https://github.com/graphql-java/graphql-java-spring to leverage functional routing and improve the WebFlux support based on what you have done in this PR, to keep only the Kofu DSL specific bits here. Any thoughts?

Ok. I will refactor https://github.com/graphql-java/graphql-java-spring.

> Also I would be interested to to know if you have checked that the `graphql-java` async supports is really non-blocking and not based on blocking code running on a thread pool via a dedicated executor.

https://spectrum.chat/graphql-java/general/how-do-create-graphql-java-spring-webflux-based-data-fetcher-if-my-data-fetcher-returns-mono-it-is-throwing-error~19defe59-f91b-4db4-8296-78c0dcd90a38

**Comment by sdeleuze** [comment]
Interesting link thanks.

For `graphql-java-spring` I think it is possible to bump Spring Framework to 5.2 milestone and Spring Boot to 2.2 milestone and leverage functional routing for both WebMvc and WebFlux since Spring Boot supports `RouterFunction` beans in annotated controller applications.

If you follow the same logic than in your PR, that will significantly improve the quality of `graphql-java-spring` WebFlux support which seems not production ready in its current form.

That give us the time to iterate with `graphql-java` project lead before Boot and Framework GA.

**Comment by sdeleuze** [comment]
@FVershinin Could you please rework this PR to try to integrate the WIP new Spring GraphQL support incubating in https://github.com/spring-projects-experimental/spring-graphql? If you face functional specific issues, please create an issue in this project. If you need more guidance (not much documentation right now) please ask guidance here.

**Comment by FVershinin** [comment]
Ok

**Comment by sdeleuze** [comment]
Given the amount of changes requiring by leveraging https://github.com/spring-projects-experimental/spring-graphql I close this PR, GraphQL support being tracked by #207. Please create an new PR when/if you have something.

**Pull request closed without merging**
